config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    unlocks:  'admins/unlocks'
  }

  get :admin,               to: 'admins/admins#show'
  get 'admin/projects',     to: 'admins/admins#show'
  get 'admin/categories',   to: 'admins/admins#categories'
  get 'admin/technologies', to: 'admins/admins#technologies'
  get 'admin/contributors', to: 'admins/admins#contributors'

  resources :projects,     only: [:index, :edit, :show, :create, :update, :destroy]
  resources :contributors, only: [:index, :edit, :show, :create, :update, :destroy]
  resources :technologies, only: [:edit, :create, :update, :destroy]
  resources :categories,   only: [:edit, :create, :update, :destroy]

  # API
  get 'api/projects', to: 'api#projects'

  root 'projects#index'
end

app/views/admins/admins/categories.html.erb
<% provide :title, 'Categories' %>

<div class="d-flex align-items-center">
  <h3>Categories</h3>
  <button class="btn btn-primary ml-3" data-toggle="modal" data-target="#addCategoryModal">+ Add New</button>

  <div class="modal fade" id="addCategoryModal" tabindex="-1" role="dialog" aria-labelledby="addCategoryModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="addCategoryModalLabel">Add New Category</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <%= form_for @new_category, url: categories_path, remote: true do |f| %>
            <div class="form-group">
              <%= f.label :name %>
              <%= f.text_field :name, class: 'form-control' %>
            </div>

            <div class="form-group">
              <%= f.submit 'Add', class: 'btn btn-primary' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Projects</th>
    </tr>
  </thead>
  <% @categories.each do |c| %>
    <tr>
      <td><%= c.name %></td>
      <td><%= c.projects_count %></td>
      <td><%= link_to raw("<i class='fa fa-edit'></i>"), edit_category_path(c), remote: true, class: 'text-info' %></td>
      <td><%= link_to raw("<i class='fa fa-trash'></i>"), category_path(c), method: :delete, class: 'text-danger' %></td>
    </tr>
  <% end %>
</table>

app/views/admins/admins/contributors.html.erb
<% provide :title, 'Contributors' %>

<div class="d-flex align-items-center">
  <h3>Contributors</h3>
  <button class="btn btn-primary ml-3" data-toggle="modal" data-target="#addContributorModal">+ Add New</button>

  <div class="modal fade" id="addContributorModal" tabindex="-1" role="dialog" aria-labelledby="addContributorModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="addContributorModalLabel">Add New Contributor</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <%= form_for @new_contributor, url: contributors_path, remote: true do |f| %>
            <div class="row">
              <div class="col-4">
                <%= image_tag @new_contributor.image.url, id: 'add-avatar' %>
              </div>
              <div class="col-7 custom-file">
                <%= f.file_field :image, class: 'custom-file-input', id: 'avatar-uploader' %>
                <%= f.label 'Avatar', class: 'custom-file-label', for: 'avatar-uploader' %>
              </div>
            </div>
            <div class="form-group mt-4">
              <%= f.label :name %>
              <%= f.text_field :name, class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.label :email %>
              <%= f.text_field :email, class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.label :join_date %>
              <%= f.date_field :join_date, class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.label :left_date %>
              <%= f.date_field :left_date, class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.label :technologies %>
              <select class="multi-select" name="technologies[]" multiple="multiple">
                <% @technologies.each do |t| %>
                  <option value="<%= t[:title] %>"><%= t[:title] %></option>
                <% end %>
              </select>
            </div>
            <div class="form-group">
              <%= f.label :description %>
              <%= f.text_area :description, id: 'editor', class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.submit 'Add', class: 'btn btn-primary' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Projects</th>
      <th>Technologies</th>
    </tr>
  </thead>
  <% @contributors.each do |c| %>
    <tr>
      <td><%= c.name %></td>
      <td><%= c.projects_count %></td>
      <td><%= c.technologies.size %></td>
      <td><%= link_to raw("<i class='fa fa-edit'></i>"), edit_contributor_path(c), remote: true, class: 'text-info' %></td>
      <td><%= link_to raw("<i class='fa fa-trash'></i>"), contributor_path(c), method: :delete, class: 'text-danger' %></td>
    </tr>
  <% end %>
</table>

<script src="https://cdn.ckeditor.com/ckeditor5/20.0.0/classic/ckeditor.js"></script>
<script>
  $('.multi-select').select2({
    theme: "bootstrap",
    tags: true
  })
  
  ClassicEditor
    .create( document.querySelector( '#editor' ) )
    .catch( error => {
        console.log( error )
    } )
</script>

app/views/admins/admins/show.html.erb
<%= provide :title, 'Projects' %>

<div class="d-flex align-items-center">
  <h3>Projects</h3>
  <button class="btn btn-primary ml-3" data-toggle="modal" data-target="#addProjectModal">+ Add New</button>

  <div class="modal fade" id="addProjectModal" tabindex="-1" role="dialog" aria-labelledby="addProjectModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="addProjectModalLabel">Add New Project</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <%= form_for @new_project, url: projects_path, remote: true do |f| %>
            <div class="row">
              <div class="col-4">
                <%= image_tag @new_project.image.url, id: 'featured-image-preview' %>
              </div>
              <div class="col-7 custom-file">
                <%= f.file_field :image, class: 'custom-file-input', id: 'featured-image-editor' %>
                <%= f.label 'Featured Image', class: 'custom-file-label', for: 'featured-image-editor' %>
              </div>
            </div>
            <div class="form-group mt-4">
              <%= f.label :title %>
              <%= f.text_field :title, class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.label :start_date %>
              <%= f.date_field :start_date, class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.label :finish_date %>
              <%= f.date_field :finish_date, class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.label :technologies %>
              <select class="multi-select tags" name="technologies[]" multiple="multiple">
                <% @technologies.each do |t| %>
                  <option value="<%= t[:title] %>"><%= t[:title] %></option>
                <% end %>
              </select>
            </div>
            <div class="form-group">
              <%= f.label :categories %>
              <select class="multi-select tags" name="categories[]" multiple="multiple">
                <% @categories.each do |t| %>
                  <option value="<%= t[:name] %>"><%= t[:name] %></option>
                <% end %>
              </select>
            </div>
            <div class="form-group">
              <%= f.label :contributors %>
              <select class="multi-select" name="contributors[]" multiple="multiple">
                <% @contributors.each do |c| %>
                  <option value="<%= c[:id] %>"><%= c[:name] %></option>
                <% end %>
              </select>
            </div>
            <div class="form-group">
              <%= f.label :description %>
              <%= f.text_area :description, id: 'editor', class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.submit 'Add', class: 'btn btn-primary' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Categories</th>
      <th>Technologies</th>
      <th>Contributors</th>
    </tr>
  </thead>
  <% @projects.each do |p| %>
    <tr>
      <td><%= p.title %></td>
      <td><%= p.categories_count %></td>
      <td><%= p.technologies.size %></td>
      <td><%= p.contributors.size %></td>
      <td><%= link_to raw("<i class='fa fa-edit'></i>"), edit_project_path(p), remote: true, class: 'text-info' %></td>
      <td><%= link_to raw("<i class='fa fa-trash'></i>"), project_path(p), method: :delete, class: 'text-danger' %></td>
    </tr>
  <% end %>
</table>

<script src="https://cdn.ckeditor.com/ckeditor5/20.0.0/classic/ckeditor.js"></script>
<script>
  $('.multi-select').select2({
    theme: "bootstrap"
  })
  $('.multi-select.tags').select2({
    theme: "bootstrap",
    tags: true
  })
  
  ClassicEditor
    .create( document.querySelector( '#editor' ) )
    .catch( error => {
        console.log( error )
    } )
</script>

app/views/admins/admins/technologies.html.erb
<% provide :title, 'Technologies' %>

<div class="d-flex align-items-center   ">
  <h3>Technologies</h3>
  <button class="btn btn-primary ml-3" data-toggle="modal" data-target="#addTechnologyModal">+ Add New</button>

  <div class="modal fade" id="addTechnologyModal" tabindex="-1" role="dialog" aria-labelledby="addNewTechnologyModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="addNewTechnologyModalLabel">Add New Technology</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <%= form_for @new_technology, url: technologies_path, remote: true do |f| %>
            <div class="form-group">
              <%= f.label :title %>
              <%= f.text_field :title, class: 'form-control' %>
            </div>

            <div class="form-group">
              <%= f.submit 'Add', class: 'btn btn-primary' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Projects</th>
    </tr>
  </thead>
  <% @technologies.each do |t| %>
    <tr>
      <td><%= t.title %></td>
      <td><%= t.projects_count %></td>
      <td><%= link_to raw("<i class='fa fa-edit'></i>"), edit_technology_path(t), remote: true, class: 'text-info' %></td>
      <td><%= link_to raw("<i class='fa fa-trash'></i>"), technology_path(t), method: :delete, class: 'text-danger' %></td>
    </tr>
  <% end %>
</table>