config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    unlocks:  'admins/unlocks'
  }

  get :admin,               to: 'admins/admins#show'
  get 'admin/projects',     to: 'admins/admins#show'
  get 'admin/categories',   to: 'admins/admins#categories'
  get 'admin/technologies', to: 'admins/admins#technologies'
  get 'admin/contributors', to: 'admins/admins#contributors'

  resources :projects,     only: [:index, :edit, :show, :create, :update, :destroy]
  resources :contributors, only: [:index, :edit, :show, :create, :update, :destroy]
  resources :technologies, only: [:edit, :create, :update, :destroy]
  resources :categories,   only: [:edit, :create, :update, :destroy]

  # API
  get 'api/projects', to: 'api#projects'

  root 'projects#index'
end

app/views/layouts/_footer.html.erb
    <footer class="site-footer footer-light" style="background-color: #222222;">
      <div class="container">
        <div class="footer-row">
          <div class="row">
            <div class="col-md-3 col-sm-6">
              <section id="silicon_contacts-2" class="widget widget_silicon_contacts">
                <h3 class="widget-title">Contact Us</h3>
                <ul>
                  <li> <i class="fa fa-map-marker background-white"></i> <span class="contact-label">Find Us</span> <span class="contact-info font-family-body">123, Wallstreet, NY, New York, US.</span></li>
                  <li> <i class="fa fa-phone background-white"></i> <span class="contact-label font-family-nav">Call Us</span> <a href="tel:(203)676-8299" class="contact-info font-family-body">(+1) 111-1111</a></li>
                  <li> <i class="fa fa-envelope background-white"></i> <span class="contact-label font-family-nav">Write Us</span> <a href="mailto:info@techno-soft.com" class="contact-info font-family-body">info@techno-soft.com</a></li>
                </ul>
              </section>
            </div>
            <div class="col-md-3 col-sm-6">
              <section id="custom_html-2" class="widget_text widget widget_custom_html">
                <h3 class="widget-title">Our Company</h3>
                <div class="textwidget custom-html-widget"><a style="font-size: 15px; color: white;" href="https://techno-soft.com/about.html">About Us</a> <br>
                  <br>
                  <a style="font-size: 15px; color: white;" href="https://techno-soft.com/healthcare-software-development.html">Healthcare Services</a> <br>
                  <br>
                  <a style="font-size: 15px; color: white;" href="https://techno-soft.com/why-technosoft.html">Why Technosoft</a> <br>
                  <br>
                  <a style="font-size: 15px; color: white;" href="https://techno-soft.com/faqs.html">FAQs</a> <br>
                  <br>
                  <a style="font-size: 15px; color: white;" href="https://techno-soft.com/healthcare-it-blog.html">Tech Blog</a> <br>
                  <br>
                  <a style="font-size: 15px; color: white;" href="https://techno-soft.com/careers.html">Careers</a></div>
              </section>
            </div>
            <div class="clearfix visible-sm"></div>
            <div class="col-md-3 col-sm-6"></div>
            <div class="col-md-3 col-sm-6">
              <section id="text-4" class="widget widget_text">
                <h3 class="widget-title">SUCCESS REPEATED</h3>
                <div class="textwidget">
                  <p>It is a pride that over 90% of our work comes from our existing customers. Our customers who once start working with us are staying with us. It is the result of our Perfect Software Development Process.</p>
                </div>
              </section>
              <section id="silicon_socials-2" class="widget widget_silicon_socials">
                <div class="social-bar text-left"><a href="https://www.facebook.com/technosoftsolutionsinc/" class="social-button sb-facebook sb-shape-circle sb-monochrome sb-light border-default" data-toggle="tooltip" data-placement="top" title="" data-original-title="Facebook"> <i class="socicon-facebook unhvrd"></i> <i class="socicon-facebook hvrd"></i> </a><a href="https://twitter.com/techno_soft" class="social-button sb-twitter sb-shape-circle sb-monochrome sb-light border-default" data-toggle="tooltip" data-placement="top" title="" data-original-title="Twitter"> <i class="socicon-twitter unhvrd"></i> <i class="socicon-twitter hvrd"></i> </a><a href="https://www.linkedin.com/company/technosoft-solutions_2/" class="social-button sb-linkedin sb-shape-circle sb-monochrome sb-light border-default" data-toggle="tooltip" data-placement="top" title="" data-original-title="LinkedIn"> <i class="socicon-linkedin unhvrd"></i> <i class="socicon-linkedin hvrd"></i> </a><a href="https://www.pinterest.com/technosoftsolutions/" class="social-button sb-pinterest sb-shape-circle sb-monochrome sb-light border-default" data-toggle="tooltip" data-placement="top" title="" data-original-title="Pinterest"> <i class="socicon-pinterest unhvrd"></i> <i class="socicon-pinterest hvrd"></i> </a></div>
              </section>
            </div>
          </div>
        </div>
        <div class="footer-row border-default-top">
          <section id="text-2" class="widget widget_text">
            <div class="textwidget">
              <div class="social-bar text-center" style="margin-bottom: 5px;"></div>
              <p class="text-center">© 2020 Technosoft Solutions – <a href="https://techno-soft.com/offshore-software-development.html">Offshore Healthcare Software Development</a>. All rights reserved.</p>
            </div>
          </section>
        </div>
      </div>
    </footer>
  </main>
  <link rel="stylesheet" href="https://d1azc1qln24ryf.cloudfront.net/114779/Socicon/style-cf.css?u8vidh" />
</body>
</html>

app/views/layouts/_head-pdf.pdf.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= wicked_pdf_stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= wicked_pdf_javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <main class="page-wrapper">

app/views/layouts/_head.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <main class="page-wrapper">

app/views/layouts/_header.html.erb
<header class="site-header header-fullwidth">
  <div class="topbar font-family-nav background-solid topbar-dark-skin" style="background-color: #f5f5f5;">
    <div class="topbar-inner">
      <div class="topbar-inner-column">
        <div class="additional-info hidden-sm hidden-xs">
          <!--a href="tel:(+1) 111-1111"><i class="si si-phone"></i> (+1) 111-1111</a>&nbsp;&nbsp;&nbsp;&nbsp;-->
          <a href="mailto:info@techno-soft.com"><i class="fa fa-email-border">&nbsp;</i>info@techno-soft.com</a>
        </div>
        <div class="social-bar text-no">
          <a href="https://www.facebook.com/technosoftsolutionsinc/" class="social-button sb-facebook sb-shape-no sb-monochrome sb-dark"> <i class="socicon-facebook unhvrd"></i> <i class="socicon-facebook hvrd"></i> </a>
          <a href="https://www.linkedin.com/company/technosoft-solutions_2/" class="social-button sb-linkedin sb-shape-no sb-monochrome sb-dark"> <i class="socicon-linkedin unhvrd"></i> <i class="socicon-linkedin hvrd"></i> </a>
          <a href="https://twitter.com/techno_soft" class="social-button sb-twitter sb-shape-no sb-monochrome sb-dark"> <i class="socicon-twitter unhvrd"></i> <i class="socicon-twitter hvrd"></i> </a>
          <a href="https://www.pinterest.com/technosoftsolutions/" class="social-button sb-pinterest sb-shape-no sb-monochrome sb-dark"> <i class="socicon-pinterest unhvrd"></i> <i class="socicon-pinterest hvrd"></i> </a>
        </div>
      </div>
      <div class="topbar-inner-column"></div>
    </div>
  </div>
  <div class="navbar-horizontal navbar-ghost menu-skin-dark border-default-bottom" style="">
    <div class="site-search">
      <div class="inner">
        <div class="search-form">
          <form method="get" class="search-box" action="https://techno-soft.com/" autocomplete="off"> <input type="text" name="s" placeholder="Search" value=""> <button type="submit"><i class="fa fa-search"></i></button></form>
          <div class="search-tools font-family-nav"> <span class="search-clear">Clear</span> <span class="search-close"><i class="si si-cross"></i></span></div>
        </div>
      </div>
    </div>
    <div class="navbar-inner">
      <div class="navbar-branding">
        <div class="mobile-menu-toggle"> <i class="si si-menu"></i></div>
        <a href="https://techno-soft.com/" class="site-logo" rel="home" itemprop="url" style="width: 75px;"><img src="https://techno-soft.com/wp-content/uploads/2018/06/cropped-logo-1-1-e1529661190841.png" class="custom-logo" alt="" itemprop="logo" width="150" height="158"></a><a href="https://techno-soft.com/" class="mobile-logo" style="width: 75px;"><img src="https://techno-soft.com/wp-content/uploads/2018/06/logo-1-1-e1529661190841.png" class="attachment-full size-full" alt="Technosoft Solutions logo" width="150" height="158"></a></div>
      <div class="navbar-utils font-family-nav">
        <div class="inner">
          <div class="util site-search-toggle"> <i class="fa fa-search"></i></div>
          <div class="util site-button">
            <section class="widget widget_silicon_button">
              <h2 class="widget-title">Contact Us</h2>
              <a href="https://techno-soft.com/contact.html" class="btn btn-solid btn-pill btn-danger btn-nl btn-block waves-effect waves-light">Contact Us</a><span class="text-sm text-gray"></span></section>
          </div>
        </div>
      </div>
    </div>
    <div class="menu-wrap"><nav class="main-navigation font-family-nav">
        <ul id="menu-export-menu-1" class="menu">
          <li class="menu-item menu-item-type-custom menu-item-object-custom current-menu-item current-menu-ancestor current-menu-parent menu-item-1240"><%= link_to 'Projects', root_path %></li>
          <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1242"><%= link_to 'Contributors', contributors_path %></li>
          <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1243"><a href="https://techno-soft.com/about.html">About</a></li>
          <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1244"><a href="#">Contact</a></li>
          <% if admin_signed_in? %>
            <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1244"><%= link_to 'Admin Panel', admin_path %></li>
            <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1244"><%= link_to 'Logout', destroy_admin_session_path, method: :delete %></li>
          <% end %>
        </ul>
      </nav></div>
  </div>
  <div class="navbar-horizontal navbar-sticky menu-skin-dark border-default-bottom" style="background-color: rgb(255, 255, 255); display: none;">
    <div class="site-search">
      <div class="inner">
        <div class="search-form">
          <form method="get" class="search-box" action="https://techno-soft.com/" autocomplete="off"> <input type="text" name="s" placeholder="Search" value=""> <button type="submit"><i class="si si-search"></i></button></form>
          <div class="search-tools font-family-nav"> <span class="search-clear">Clear</span> <span class="search-close"><i class="fa fa-cross"></i></span></div>
        </div>
      </div>
    </div>
    <div class="navbar-inner">
      <div class="navbar-branding">
        <div class="mobile-menu-toggle"> <i class="fa fa-menu"></i></div>
        <a href="https://techno-soft.com/" class="site-logo" rel="home" itemprop="url" style="width: 75px;"><img src="https://techno-soft.com/wp-content/uploads/2018/06/logo-1-1-e1529661190841.png" class="custom-logo" alt="Technosoft Solutions logo" itemprop="logo" width="150" height="158"></a></div>
      <div class="navbar-utils font-family-nav">
        <div class="inner">
          <div class="util site-search-toggle"> <i class="fa fa-search"></i></div>
          <div class="util site-button">
            <section class="widget widget_silicon_button">
              <h2 class="widget-title">Contact Us</h2>
              <a href="https://techno-soft.com/contact.html" class="btn btn-solid btn-pill btn-danger btn-nl btn-block waves-effect waves-light">Contact Us</a><span class="text-sm text-gray"></span></section>
          </div>
        </div>
      </div>
    </div>
    <div class="menu-wrap"><nav class="main-navigation font-family-nav">
        <ul id="menu-export-menu-2" class="menu">
          <li class="menu-item menu-item-type-custom menu-item-object-custom current-menu-item current-menu-ancestor current-menu-parent menu-item-1240"><%= link_to 'Projects', root_path %></li>
          <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1242"><%= link_to 'Contributors', contributors_path %></li>
          <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1243"><a href="https://techno-soft.com/about.html">About</a></li>
          <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1244"><a href="#">Contact</a></li>
        </ul>
      </nav></div>
  </div>
</header>

<% if !flash.empty? %>
  <div id="notifications" class="my-3 mx-5">
    <% flash.each do |message_type, message| %>
      <%
        # swap devise flash keys for bootstrap ones
        case message_type
          when 'alert'
            message_type = 'warning'
          when 'notice'
            message_type = 'info'
          when 'error'
            message_type = 'danger'
        end
      %>
      <%= content_tag(:div, raw(message + '<button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>'), class: "alert alert-#{message_type} alert-dismissible fade show", role: :alert) %>
    <% end %>
  </div>
<% end %>

app/views/layouts/admin.html.erb
<% provide :title, " | Admin Panel" %>
<%= render 'layouts/head' %>
<%= render 'layouts/header' %>

<div class="content-wrapper">
  <div class="container-fluid my-5">
    <div class="row">
      <aside class="col-3">
        <nav class="nav flex-column">
          <%= link_to 'Projects',     admin_projects_path, class: "nav-link active" %>
          <%= link_to 'Categories',   admin_categories_path, class: "nav-link" %>
          <%= link_to 'Technologies', admin_technologies_path, class: "nav-link" %>
          <%= link_to 'Contributors', admin_contributors_path, class: "nav-link" %>
        </nav>
      </aside>
      <main class="col-9">
        <%= yield %>
      </main>
    </div>
  </div>
</div>

<%= render 'layouts/footer' %>

app/views/layouts/application.html.erb
<%= render 'layouts/head' %>
<%= render 'layouts/header' %>

<div class="content-wrapper">
  <%= yield %>
</div>

<%= render 'layouts/footer' %>

app/views/layouts/pdf.pdf.erb
<%= render 'layouts/head-pdf' %>

<div class="content-wrapper">
  <%= yield %>
</div>